### ISSUE TITLE
License for the WishTreeApplication

### ISSUE THREAD

**Issue by mystcb** [TokonatsuFestival/WishTreeApplication#1]
Raising issue so that we can decide on the License for the WishTreeApplication, currently, the choices is between:

* CC-SA-BY 4.0 - This will require anyone adapting the work to share under the same license
* CC-SA 4.0 - This does not require anyone adapting the work to share under the same license

The former is not recommended for software.

 My recommendation would be the standard CC-SA 4.0 license.

**Comment by Yamakiroshi** [comment]
Added new license file with latest commit (ahhh I failed to do it in a PR>_<) but it is now included and have learnt my lesson again (been a while) But yes, I have included the CC BY 4.0 License for this project!
